### ISSUE TITLE
Vortex Update Detection

### ISSUE THREAD

**Issue by naqaden** [alandtse/skyrim_vr_address_library#22]
Here's a little timeline of my experience, partly explained in https://github.com/alandtse/PapyrusExtenderSSE/issues/1#issuecomment-1330395940:

- I started with 0.36.0
- Vortex detected updates as expected up to 0.48.0.
- The "v" prefix started on v0.50.0. Vortex didn't consider it an update.
- 0.52.0 released without the prefix. Vortex didn't consider it an update.
- I manually updated to v0.65.0 to see if Vortex would detect v0.66.0, and it did.
- Now similarly to 0.52.0, Vortex doesn't consider 0.67.1 an update.

Apparently, the existence of any prefixed version turns Vortex blind to non-prefixed versions. I suspect even if the prefixes could be removed from old versions, it wouldn't help players currently on a prefixed version. So I think the lesser evil is to continue prefixing at this point, unless a third version format can set Vortex straight by showing up as an update regardless of a player's current version.

**Comment by alandtse** [comment]
I just deleted all old versions and removed the prefix version. It may mess stuff up in the short term but hopefully ti'll make the long term more sustainable.
